# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 01d5d3a29ea71fba47c3d0ee662293efc7db1c618b75d25ef0a4da0abc46ad708c26e8a4bbbb1f9b81d1bedf046c52b855bbe055138d79ca9bbe7a95b51dcbed

test:
  secret_key_base: 7e72429f6cb5438fc28f10a51d376177a3d8a99214d85f7a0ca9607405be21718c3f564892c24e5e2c48cb9ce54f7f2834844e8430a447c57b4e36408510a730

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
